name: 数据同步

on:
  schedule:
  - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - name: Use Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'
      
    - name: Update
      run: | 
        yarn
        GITHUB_TOKEN=${{secrets.TOKEN}} npm run update:data
