name: 数据同步

on:
  schedule:
  - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    
    steps:
    - name: 数据同步
    - run: yarn
    - run: GITHUB_TOKEN=${{secrets.TOKEN}} npm run update:data
