name: 数据同步

on:
  schedule:
  - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    
    steps:
    - uses: actions/checkout@v3
    - name: 数据同步
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
    - run: yarn
    - run: GITHUB_TOKEN=${{secrets.TOKEN}} npm run update:data
